### ISSUE TITLE
Uglify only files used

### ISSUE THREAD

**Issue by DHoffm** [gruntjs/grunt-contrib-requirejs#104]
Hi,

I'm using the optimize option with "uglify" and noticed that all files in my app folder are compressed wether there already compressed or not or if there really used by my app or not. What are the correct settings to exclude those files?

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
