### ISSUE TITLE
The Usage example in the README doesn't work

### ISSUE THREAD

**Issue by greggman** [gruntjs/grunt-contrib-requirejs#111]
Yea I know, I must be stupid but....

Here's my options

```    
    requirejs: {
      compile: {
        options: {
          baseUrl: "./",
          name: "node_modules/almond/almond.js",
          mainConfigFile: "config.js",
          out: "dist/app.js",
        }
     }
```
And here's my `config.js`

```
require.config({
});
require( ["src/main"], function(main) {
});
```

And when I check the output there's nothing in it except almond. `src/main.js` has not been pulled in

[Here's an example](https://github.com/greggman/grunt-contrib-requirejs-example)

You can look [`src/main.js`](https://github.com/greggman/grunt-contrib-requirejs-example/blob/master/src/main.js) and you can see it's not in [`dist/app.js`](https://github.com/greggman/grunt-contrib-requirejs-example/blob/master/dist/app.js)

What am I not getting?

**Comment by jklapuch** [comment]
This works for me:

```
requirejs: {
      compile: {
        options: {
          baseUrl: "./",
          name: "node_modules/almond/almond.js",
          mainConfigFile: "config.js",
          include: ['src/main.js']
          out: "dist/app.js",
        }
     }
```

**Comment by greggman** [comment]
Thanks! I send you a pull request to update the README. Maybe you have some other idea of what you'd like there. I was trying to debug some issues and thought I'd start with whatever works but since the usage in the readme didn't work I wasn't sure what the correct thing was.
