### ISSUE TITLE
How you are performing optimization in this plugin.

### ISSUE THREAD

**Issue by hardy91** [gruntjs/grunt-contrib-requirejs#113]
As i  was searching around the whole web , everywhere i got that this plugin performs optimization where my query is to know that how optimization getting performed inside this plugin.

As we are going to use this library in our project, so it is important aspect to know that how optimization is going on inside this plugin .

**Comment by amenadiel** [comment]
This plugin just delegates to r.js. every option you can pass corresponds to a parameter you could pass to the CLI.

In turn, r.js doesn't optimize by itself. After performing concatenation it can optimize through uglifyJS or closure compiler. Again, the specific optimization parameters (mangle, screw-ie8, etc) are just forwarded to the optimization library
