### ISSUE TITLE
Arrow functions

### ISSUE THREAD

**Issue by nelson777** [gruntjs/grunt-contrib-requirejs#121]
I'm getting an error when using arrow functions:

Error: Cannot uglify file: /home/77363698953/dados/des/js/iDMT/www/js/prj.min.js. Skipping it. Error is:
SyntaxError: Unexpected token: operator (>) (line: 2720, col: 11, pos: 616843)

I think this is somewhat related with UglifyJs version ? Does this mean I can't use arrow functions ?

**Comment by nelsieborja** [comment]
It seems you are using latest JS.. Check [here](https://github.com/requirejs/r.js/issues/959#issuecomment-317424745) it may also be your solution.

**Comment by nelson777** [comment]
Worked great thanks. Closing as there is another topic on this subject.
