### ISSUE TITLE
Almond support

### ISSUE THREAD

**Issue by dabroek** [gruntjs/grunt-contrib-requirejs#24]
The support for almond is not very well documented. I have seen the use of the "name" attribute to reference the almond lib. Since almond is mentioned in the example.build.js file, I assume that it is already possible to configure almond as replacement for require. But it's still quite unclear. 

Next to that I am also curious how the "include" and "insertRequire" options relate to the "name" option. Can anyone explain?

**Comment by PedroEsperanca** [comment]
Is there same way to get the almond code to run ?
If I use these configurations my code does nothing :s 
I can see that some libraries have loaded like jquery because I can call them from the console, but figure out how to bootstrap the app
