### ISSUE TITLE
error with multiple targets

### ISSUE THREAD

**Issue by matiasfha** [gruntjs/grunt-contrib-requirejs#63]
I try to use this with multiple targets, this is the configuration
    requirejs:{
            app:{
                options:{
                    baseUrl:'.tmp/scripts',
                    optimize:'none',
                    mainConfigFile:'.tmp/scripts/main.js',
                    out:'<%= yeoman.dist %>/scripts/scripts.js'
                }

```
        },
        public:{

            options:{
                baseUrl:'.tmp/scripts',
                optimize:'none',
                mainConfigFile:'public/scripts/main.js',
                out:'<%= yeoman.dist %>/scripts/scripts_public.js'
            }

        }

    }
```

But, when grunt try to run the targets i get and error:
Running "requirejs:compile" (requirejs) task
Verifying property requirejs.compile exists in config...ERROR

> > Unable to process task.
> > Warning: Required config property "requirejs.compile" missing. Use --force to continue.

When i try to update the configuration to add the compile task in each of target, or using surrounding the targets, i get wrong configuration. (the task use default options and not the configured) like this

requirejs:
  { compile:
   { app:
      { options:
         { baseUrl: '.tmp/scripts',
           optimize: 'none',
           mainConfigFile: '.tmp/scripts/main.js',
           out: 'dist/scripts/scripts.js' } },
     public:
      { options:
         { baseUrl: '.tmp/scripts',
           optimize: 'none',
           mainConfigFile: 'public/scripts/main.js',
           out: 'dist/scripts/scripts_public.js' } },
     options:
      { name: 'main',
        out: 'dist/scripts/scripts.js',
        baseUrl: 'scripts',
        mainConfigFile: 'scripts/main.js' } } }

How can i configure this two targets?

**Comment by averma1989** [comment]
I was doing  : 

`requirejs: {
      compile: {
        options: {
          appDir: '<%= yeoman.app %>',
          baseUrl : 'scripts',
          optimize: 'uglify2',
          mainConfigFile: 'app/scripts/main.js',
          dir: 'dist',
          modules: [{
                name: 'bootstrap',
          },{
            name: 'controllers/homeCtrl',
            exclude :[
              'bootstrap'
            ]
          },{
            name: 'controllers/listingsCtrl',
            exclude :[
              'bootstrap'
            ]
          },{
            name: 'controllers/projectDetailCtrl',
            exclude :[
              'bootstrap'
            ]
          },{
            name: 'controllers/staticPageCtrl',
            exclude :[
              'bootstrap'
            ]
          },{
            name: 'controllers/mapListingsCtrl',
            exclude :[
              'bootstrap'
            ]
          },{
            name: 'controllers/overviewCtrl',
            exclude :[
              'bootstrap'
            ]
          },
          {
            name: 'controllers/portfolioIndexCtrl',
            exclude :[
              'bootstrap'
            ]
          },
          {
            name: 'controllers/compare',
            exclude: [
              'bootstrap'
            ]
          },
          {
            name: 'controllers/testimonialCtrl',
            exclude: [
              'bootstrap'
            ]
          },
          {
            name: 'controllers/careersCtrl',
            exclude: [
              'bootstrap'
            ]
          }]
        }
      },
      compileMobile: {
        options: {
          appDir: '<%= yeoman.app %>',
          baseUrl : 'scripts/livability',
          optimize: 'uglify2',
          mainConfigFile: 'app/scripts/livability/main.js',
          dir: 'dist',
          modules: [{
                name: 'bootstrap'
          }]
        }
      }
    }

  grunt.registerTask('build', [
    // 'genLangFiles',
    'clean:dist',
    'compass:dist',
    'useminPrepare',
    'concurrent:dist',
    'autoprefixer',
    'imagemin',
    'concat',    
    'cdnify',
    'copy:dist',
    'requirejs:compile',
    'requirejs:compileMobile',
    'ngmin',
    'cssmin',
    'htmlmin',
    'uglify',
    'filerev',
    'updateVersion', 
    'usemin',
    'cdn'
  ]);`

After reading above comment, I did : 
`requirejs: {
      compileWebapp: {
        options: {
          appDir: '<%= yeoman.app %>',
          baseUrl : 'scripts',
          optimize: 'uglify2',
          mainConfigFile: 'app/scripts/main.js',
          dir: 'dist',
          modules: [{
                name: 'bootstrap',
          },{
            name: 'controllers/homeCtrl',
            exclude :[
              'bootstrap'
            ]
          },{
            name: 'controllers/listingsCtrl',
            exclude :[
              'bootstrap'
            ]
          },{
            name: 'controllers/projectDetailCtrl',
            exclude :[
              'bootstrap'
            ]
          },{
            name: 'controllers/staticPageCtrl',
            exclude :[
              'bootstrap'
            ]
          },{
            name: 'controllers/mapListingsCtrl',
            exclude :[
              'bootstrap'
            ]
          },{
            name: 'controllers/overviewCtrl',
            exclude :[
              'bootstrap'
            ]
          },
          {
            name: 'controllers/portfolioIndexCtrl',
            exclude :[
              'bootstrap'
            ]
          },
          {
            name: 'controllers/compare',
            exclude: [
              'bootstrap'
            ]
          },
          {
            name: 'controllers/testimonialCtrl',
            exclude: [
              'bootstrap'
            ]
          },
          {
            name: 'controllers/careersCtrl',
            exclude: [
              'bootstrap'
            ]
          }]
        }
      },
      compileMobile: {
        options: {
          appDir: '<%= yeoman.app %>',
          baseUrl : 'scripts/livability',
          optimize: 'uglify2',
          mainConfigFile: 'app/scripts/livability/main.js',
          dir: 'dist',
          modules: [{
                name: 'bootstrap'
          }]
        }
      }
    }

grunt.registerTask('build', [
    // 'genLangFiles',
    'clean:dist',
    'compass:dist',
    'useminPrepare',
    'concurrent:dist',
    'autoprefixer',
    'imagemin',
    'concat',    
    'cdnify',
    'copy:dist',
    'requirejs',
    'ngmin',
    'cssmin',
    'htmlmin',
    'uglify',
    'filerev',
    'updateVersion', 
    'usemin',
    'cdn'
  ]);`

But still I am getting only one file `dist/scripts/livability/bootstrap.js` not the `dist/scripts/bootstrap.js` 
I want to build both, please suggest.
