### ISSUE TITLE
Multiple builds using dynamic file 

### ISSUE THREAD

**Issue by Blasz** [gruntjs/grunt-contrib-requirejs#87]
I'd like to utilise grunt's file mapping options (http://gruntjs.com/configuring-tasks#files), so that I can optimize multiple applications via globbing patterns and grunt's ability to build file mappings dynamically. Adding a new Gruntfile target for each new application that is added to a specific directory instead of it automatically getting picked up via basic file pattern matching creates an extra manual process that seems counter-intuitive and goes against the grunt mantra of automating tasks.

The command-line version of the requirejs optimiser takes a build configuration filename as an argument which one would assume would be able to be used in the grunt version of requirejs as well but it seems that grunt's file mapping options are not implemented at all?

If we look at [grunt-contrib-coffee](https://github.com/gruntjs/grunt-contrib-coffee) we can see that they accept the file you want to compile as input and output the resulting javascript. Imagine if instead of allowing you to set destination file mappings, you were forced to create a destination option that was completely static. You'd have to create another target for each and every coffee file you want to compile.

Now we look at the [requireJS Optimiser](https://github.com/jrburke/r.js#optimizer). It accepts as input the build configuration filepath and outputs the optimised application file (according to the `out` parameter of the configuration file). Yet for grunt-contrib-requirejs we have to specify static build configuration filepaths or embed them within the Gruntfile itself, making it impossible to build multiple applications without adding a target for each individual requirejs application we want to optimise.

**Comment by snuggles08** [comment]
Have you looked at the example build file? It explains every option, including the one your looking for.
