### ISSUE TITLE
Uglify to quote property names that contain non-ASCII characters

### ISSUE THREAD

**Issue by Raphaww** [gruntjs/grunt-contrib-requirejs#92]
I've used to use r.js directly to optimize my modules, I switched to grunt a few days ago and using the same default options I'm getting different results on my optimized code, the most important is the non-quoted properties that contains non-ASCII characters:
var foo = { "á": "a", "é": "e" }; 
compiles to:
var foo = {á: "a", é: "e"}
witch returns an error

I did a little research and found that it was an issue and that it was fixed: 
https://github.com/mishoo/UglifyJS2/commit/8fbe20001215887275b3cf053be675ebdbf331a9

but it seams that it never made it to r.js

I know about the "quote_keys" option in uglify but I thought it'll be good to report this issue

**Comment by sindresorhus** [comment]
Then open this on the r.js issue tracker and it will get fixed here when it gets fixed there.
