### ISSUE TITLE
Load a RequireJS module within a custom task

### ISSUE THREAD

**Issue by danielefenix** [gruntjs/grunt-contrib-requirejs#96]
Good morning everyone,

I am quite new with GruntJS and I wonder if it is possible to have a task that loads some RequireJs modules to process them and write the result within a JS file.

I describe my scenario:

I have a RequireJs based project with many files. I would like to concatenate/minify/ecc.. the project to deploy it and increase performances, ecc... The optimization works perfectly with the grunt-contrib-requirejs plugin. The grunt-contrib-requirejs plugin works with a main.js file and I should need to generate it dynamically. I would like to generate the main.js processing some RequireJS module of the project (call them fileA.js and fileB.js). I would like to use the generated main.js to run the grunt-contrib-requirejs plugin.

So the task sequence would be something like:

Custom Task: 1. loads fileA.js and fileB.js 2. merge them together 3. write the result of the merging within a new JS file grunt-contrib-requirejs Task: 1. use the generated main.js file to optimize the project

Do you know how can I achieve this? I don't have any kind of restrictions on the way/tools/libs to use.

Thank you very much

Daniele

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by danielefenix** [comment]
here you can find the link:

http://stackoverflow.com/questions/30350375/gruntjs-and-custom-task-require-a-requirejs-module

Thank you very much
